CRM/CRM/CRM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from crm01 import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^login/',views.login),
    url(r'^reg/',views.reg),
    url(r'^crm/',include('crm01.urls')),


]

CRM/CRM/crm01/models.py
from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager,User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField

course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True,on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
    related_name='network_consultant',on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True,on_delete=models.CASCADE )
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)
    '''
    (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))
    '''
    def show_status(self):
        color_dict = {
            'signed':'green',
            'unregistered':'red',
            'studying':'pink',
            'paid_in_full':'blue',
        }
        return '<span style="background-color: {};color:white;padding: 5px">{}</span>'.format(color_dict[self.status],self.get_status_display())
    def show_class(self):
        return ' | '.join([str(i) for i in self.class_list.all()])

    def __str__(self):
        return '{}<{}>'.format(self.qq_name,self.qq)

class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)
    def __str__(self):
        return self.name

class ContractTemplate(models.Model):
    """
    合同模板表
    """
    name = models.CharField("合同名称", max_length=128, unique=True)
    content = models.TextField("合同内容")
    date = models.DateField(auto_now=True)


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')
    def __str__(self):
        return '{}{}({})'.format(self.get_course_display(),self.semester,self.campuses)

class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户",on_delete=models.CASCADE)
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records',on_delete=models.CASCADE)
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称',on_delete=models.CASCADE)
    school = models.ForeignKey('Campuses',on_delete=models.CASCADE)
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级",on_delete=models.CASCADE)

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True,on_delete=models.CASCADE)
    customer = models.ForeignKey('Customer', verbose_name="客户",on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售",on_delete=models.CASCADE)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True,on_delete=models.CASCADE)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级",on_delete=models.CASCADE)
    teacher = models.ForeignKey('UserProfile', verbose_name="讲师",on_delete=models.CASCADE)

    class Meta:

CRM/CRM/templates/add_consultrecord.html
{% extends 'layout.html' %}

{% block xx %}
    <div class="panel panel-default">
        <div class="panel-heading">添加跟进记录</div>
        <div class="panel-body">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <form action="" method="post" novalidate>
                            {% csrf_token %}
                            {% for i in obj %}
                                <div class="form-group row {% if i.errors.0 %}has-error{% endif %}">
                                    <label for="{{ i.id_for_label }}"
                                           class="col-sm-2 control-label">{{ i.label }}</label>
                                    <div class="col-sm-10">
                                        {{ i }}
                                        <span class="help-block">{{ i.errors.0 }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                            <button type="submit">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

CRM/CRM/templates/add_customer.html
{% extends 'layout.html' %}

{% block xx %}
    <div class="panel panel-default">
        <div class="panel-heading">添加客户</div>
        <div class="panel-body">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <form action="" method="post" novalidate>
                            {% csrf_token %}
                            {% for i in customer %}
                                <div class="form-group row {% if i.errors.0 %}has-error{% endif %}">
                                    <label for="{{ i.id_for_label }}"
                                           class="col-sm-2 control-label">{{ i.label }}</label>
                                    <div class="col-sm-10">
                                        {{ i }}
                                        <span class="help-block">{{ i.errors.0 }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                            <button type="submit">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

CRM/CRM/templates/consultrecord.html
{% extends  'layout.html' %}
{% block css %}

{% endblock %}
{% block xx %}
    <div style="">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">跟进记录列表</div>
            <div class="panel-body">
                <a class="btn btn-primary" href="{% url 'add_consultrecord' %} ">增加</a>

                <div>
                    {#      注意！！！！使用GET方法传递参数，method默认是GET#}
                    <form action="" class="pull-right">
                        <label for=""><input style="float: right" type="text" class="form-control" placeholder="Search"
                                             name="query">
                            <button type="submit" class="btn btn-default" style="float: right">Submit</button>
                        </label>

                    </form>
                </div>
                <form action="" method="post" class="form-inline">
                    {% csrf_token %}
                    <select name="action" class="form-control" style="margin-top: 10px">
                        <option value="">请选择</option>
                        <option value="multi_del">删除</option>
                    </select>
                    <button style="margin-top: 20px" class="btn-primary">提交</button>
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>选择</th>
                            <th>序号</th>
                            <th>客户</th>
                            <th>跟进内容</th>
                            <th>跟进状态</th>
                            <th>跟进日期</th>
                            <th>跟进人</th>


                        </tr>
                        </thead>
                        <tbody>
                        {% for customer in all_consultrecord %}
                            <tr>
                                <td><input name="id" type="checkbox" value="{{ customer.id }}"></td>
                                <td>{{ forloop.counter }}</td>
{#                                <td>{{ customer.customer }}</td>#}
                                <td><a href="{% url 'edit_consultrecord' customer.id %}">{{ customer.customer }}</a></td>
                                <td>{{ customer.note }}</td>
                                <td>{{ customer.get_status_display }}</td>
                                <td>{{ customer.date }}</td>
                                <td>{{ customer.consultant }}</td>


                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>


                <nav aria-label="Page navigation">
                    <ul class="pagination">

                        {{ page.pager|safe }}

                    </ul>
                </nav>
            </div>


        </div>
    </div>

{% endblock %}

CRM/CRM/templates/customer_list.html
{% extends  'layout.html'%}
{% block css %}

{% endblock %}
{% block xx %}
<div style="">
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">客户列表</div>
  <div class="panel-body">
  <a class="btn btn-primary" href="{% url 'add_customer' %} ">增加</a>
  <div>
      <form action="" class="pull-right">
          <label for=""><input style="float: right" type="text" class="form-control" placeholder="Search" name="query">
          <button type="submit" class="btn btn-default" style="float: right">Submit</button></label>

      </form>
  </div>
      <form action="" method="post" class="form-inline">
        {% csrf_token %}
          <select name="action" class="form-control" style="margin-top: 10px">
              <option value="">请选择</option>
              <option value="multi_pri">放入私户</option>
              <option value="multi_pub">放入公户</option>
              <option value="multi_del">删除</option>
          </select>
      <button style="margin-top: 20px" class="btn-primary">提交</button>
          <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>选择</th>
            <th>序号</th>
            <th>QQ</th>
            <th>QQ昵称</th>
            <th>姓名</th>
            <th>性别</th>
            <th>手机号</th>
            <th>客户来源</th>
            <th>班级类型</th>
            <th>状态</th>
            <th>咨询日期</th>
            <th>销售</th>
            <th>已报班级</th>

        </tr>
        </thead>
        <tbody>
        {% for customer in all_customer %}
            <tr>
            <td><input  name="id" type="checkbox" value="{{ customer.id }}"></td>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'edit_customer' customer.id %}">{{ customer.qq }}</a></td>
            <td>{{ customer.qq_name }}</td>
            <td>{{ customer.name }}</td>
            <td>{{ customer.get_sex_display }}</td>
            <td>{{ customer.phone }}</td>
            <td>{{ customer.get_source_display }}</td>
            <td>{{ customer.get_class_type_display }}</td>
            <td>
{#                {{ customer.get_status_display }}#}
                {{ customer.show_status|safe }}
            </td>
            <td>{{ customer.date}}</td>
            <td>{{ customer.consultant|default:'暂无'}}</td>
            <td>{{ customer.show_class}}</td>

            </tr>
        {% endfor %}
        </tbody>
  </table>
      </form>


    <nav aria-label="Page navigation">
        <ul class="pagination">

            {{ page.pager|safe }}

        </ul>
    </nav>
</div>



</div>
  </div>
</div>
{% endblock %}

CRM/CRM/templates/edit_consultrecord.html
{% extends 'layout.html' %}

{% block xx %}
    <div class="panel panel-default">
        <div class="panel-heading">编辑跟进记录</div>
        <div class="panel-body">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <form action="" method="post" novalidate>
                            {% csrf_token %}
                            {% for i in obj %}
                                <div class="form-group row {% if i.errors.0 %}has-error{% endif %}">
                                    <label for="{{ i.id_for_label }}"
                                           class="col-sm-2 control-label">{{ i.label }}</label>
                                    <div class="col-sm-10">
                                        {{ i }}
                                        <span class="help-block">{{ i.errors.0 }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                            <button type="submit">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

CRM/CRM/templates/edit_customer.html
{% extends 'layout.html' %}

{% block xx %}
    <div class="panel panel-default">
        <div class="panel-heading">编辑客户</div>
        <div class="panel-body">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <form action="" method="post" novalidate>
                            {% csrf_token %}
                            {% for i in customer %}
                                <div class="form-group row {% if i.errors.0 %}has-error{% endif %}">
                                    <label for="{{ i.id_for_label }}"
                                           class="col-sm-2 control-label">{{ i.label }}</label>
                                    <div class="col-sm-10">
                                        {{ i }}
                                        <span class="help-block">{{ i.errors.0 }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                            <button type="submit">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

CRM/CRM/templates/enrollment.html
{% extends 'layout.html' %}

{% block xx %}
    <div class="panel panel-default">
        <div class="panel-heading">添加报名记录</div>
        <div class="panel-body">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <form action="" method="post" novalidate>
                            {% csrf_token %}
                            {% for i in form_obj %}
                                <div class="form-group row {% if i.errors.0 %}has-error{% endif %}">
                                    <label for="{{ i.id_for_label }}"
                                           class="col-sm-2 control-label">{{ i.label }}</label>
                                    <div class="col-sm-10">
                                        {{ i }}
                                        <span class="help-block">{{ i.errors.0 }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                            <button type="submit">提交</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

CRM/CRM/templates/enrollrecord.html
{% extends  'layout.html' %}
{% block css %}

{% endblock %}
{% block xx %}
    <div style="">
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">报名记录列表</div>
            <div class="panel-body">
                <a class="btn btn-primary" href="{% url 'add_consultrecord' %} ">增加</a>

                <div>
                    {#      注意！！！！使用GET方法传递参数，method默认是GET#}
                    <form action="" class="pull-right">
                        <label for=""><input style="float: right" type="text" class="form-control" placeholder="Search"
                                             name="query">
                            <button type="submit" class="btn btn-default" style="float: right">Submit</button>
                        </label>

                    </form>
                </div>
                <form action="" method="post" class="form-inline">
                    {% csrf_token %}
                    <select name="action" class="form-control" style="margin-top: 10px">
                        <option value="">请选择</option>
                        <option value="multi_del">删除</option>
                    </select>
                    <button style="margin-top: 20px" class="btn-primary">提交</button>
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>选择</th>
                            <th>序号</th>
                            <th>客户</th>
                            <th>报名原因</th>
                            <th>期望</th>
                            <th>协议</th>
                            <th>审核</th>
                            <th>报名日期</th>
                            <th>备注</th>
                            <th>校区</th>
                            <th>所报班级</th>
                            <th>操作</th>


                        </tr>
                        </thead>
                        <tbody>
                        {% for customer in all_consultrecord %}
                            <tr>
                                <td><input name="id" type="checkbox" value="{{ customer.id }}"></td>
                                <td>{{ forloop.counter }}</td>
{#                                <td>{{ customer.customer }}</td>#}
                                <td><a href="{% url 'edit_consultrecord' customer.id %}">{{ customer.customer }}</a></td>
                                <td>{{ customer.why_us }}</td>
                                <td>{{ customer.your_expectation }}</td>
                                <td>{{ customer.contract_agreed }}</td>
                                <td>{{ customer.contract_approved }}</td>
                                <td>{{ customer.enrolled_date }}</td>
                                <td>{{ customer.memo }}</td>
                                <td>{{ customer.school }}</td>
                                <td>{{ customer.enrolment_class }}</td>


                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>


                <nav aria-label="Page navigation">
                    <ul class="pagination">

                        {{ page.pager|safe }}

                    </ul>
                </nav>
            </div>


        </div>
    </div>

{% endblock %}

CRM/CRM/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="wrapper">
<div class="container">
<h1>Welcome</h1>
<form class="form" method="post">
    {% csrf_token %}
<input type="text" placeholder="Username" name="username">
<input type="password" placeholder="Password" name="password">
<button type="submit" id="login-button">Login</button>
    <p>{{ msg }}</p>
</form>
</div>
<ul class="bg-bubbles">
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
<li></li>
</ul>
</div>
<script type="text/javascript" src="{% static 'jQuery/jquery-2.1.1.min.js'%}"></script>
<script type="text/javascript">
{#$('#login-button').click(function(event) {#}
{#    event.preventDefault();#}
{##}
{#    $('form').fadeOut(500);#}
{#    $('.wrapper').addClass('form-success');#}
{#{);#}
{#    密码xiaohua123#}
</script>

</body>
</html>

CRM/CRM/templates/mycustomer.html
{% extends  'layout.html'%}
{% block css %}

{% endblock %}
{% block xx %}
{#<div class="panel panel-default">#}
{#  <!-- Default panel contents -->#}
{#  <div class="panel-heading">Panel heading</div>#}
{#  <div class="panel-body">#}
{#    <table class="table table-bordered table-hover">#}
{#        <thead>#}
{#        <tr>#}
{#            <th>序号</th>#}
{#            <th>QQ</th>#}
{#            <th>QQ昵称</th>#}
{#            <th>姓名</th>#}
{#            <th>性别</th>#}
{#            <th>手机号</th>#}
{#            <th>客户来源</th>#}
{#            <th>班级类型</th>#}
{#            <th>状态</th>#}
{#            <th>咨询日期</th>#}
{#            <th>销售</th>#}
{#            <th>已报班级</th>#}
{#        </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#        {% for customer in all_customer %}#}
{#            <tr>#}
{#            <td>{{ forloop.counter }}</td>#}
{#            <td>{{ customer.qq }}</td>#}
{#            <td>{{ customer.qq_name }}</td>#}
{#            <td>{{ customer.name }}</td>#}
{#            <td>{{ customer.get_sex_display }}</td>#}
{#            <td>{{ customer.phone }}</td>#}
{#            <td>{{ customer.get_source_display }}</td>#}
{#            <td>{{ customer.get_class_type_display }}</td>#}
{#            <td>#}
{#                {{ customer.get_status_display }}#}
{#                {{ customer.show_status|safe }}#}
{#            </td>#}
{#            <td>{{ customer.date}}</td>#}
{#            <td>{{ customer.consultant|default:'暂无'}}</td>#}
{#            <td>{{ customer.show_class}}</td>#}
{#            </tr>#}
{#        {% endfor %}#}
{#        </tbody>#}
{#  </table>#}
<div style="">
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">我的客户</div>
  <div class="panel-body">
  <a class="btn btn-primary" href="{% url 'add_customer' %} ">增加</a>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>序号</th>
            <th>QQ</th>
            <th>QQ昵称</th>
            <th>姓名</th>
            <th>性别</th>
            <th>手机号</th>
            <th>客户来源</th>
            <th>班级类型</th>
            <th>状态</th>
            <th>咨询日期</th>
            <th>销售</th>
            <th>已报班级</th>
            <th>跟进记录</th>
            <th>报名记录</th>
        </tr>
        </thead>
        <tbody>
        {% for customer in all_customer %}
            <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'edit_customer' customer.id %}">{{ customer.qq }}</a></td>
            <td>{{ customer.qq_name }}</td>
            <td>{{ customer.name }}</td>
            <td>{{ customer.get_sex_display }}</td>
            <td>{{ customer.phone }}</td>
            <td>{{ customer.get_source_display }}</td>
            <td>{{ customer.get_class_type_display }}</td>
            <td>
{#                {{ customer.get_status_display }}#}
                {{ customer.show_status|safe }}
            </td>
            <td>{{ customer.date}}</td>
            <td>{{ customer.consultant|default:'暂无'}}</td>
            <td>{{ customer.show_class}}</td>
            <td><a href="{% url 'consultrecord' customer.id%}">查看跟进</a></td>
            <td><a href="{% url 'enrollment_add' customer.id %}?{{ query_params }}">添加报名记录</a></td>
            </tr>
        {% endfor %}
        </tbody>
  </table>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>

                <span aria-hidden="true"><a href="/crm/mycustomer_list?page=1">&laquo;</a></span>

            </li>
            {{ page.pager|safe }}
            <li>

                <span aria-hidden="true"><a href="/crm/mycustomer_list?page={{ page.last_page }}">&raquo;</a></span>

            </li>
        </ul>
    </nav>
</div>



</div>
  </div>

{% endblock %}